apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1roe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1roe
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1roe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1roe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1roe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ltty-tenant/rhtap-demo-app/hacbs-test-project-1roe@sha256:d0367313c70e89a211afc1c917b99a00a3ee10e000e6f41c6c69688c91e02afa
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
